name: Building the container for Model
on: 
  push: 
     brnaches: [ "main" ]
jobs:
  docker:
     name: build container
     runs_on: ubuntu-latest
     steps:
       - name: checkout
         uses: actions/checkout@v4
       - name: docker login
         uses: docker/login-actions@v3
         with: 
           username: ${{ secrets.DOCKER_PASSWORD }}
           password: ${{ secrets.DOCKER_USERNAME }}
       - name: docker build
         run: docker build  -t ${{ secrets.DOCKER_USERNAME }}/landpred:latest .
       - name: docker push
         run: docker push ${{ secrets.DOCKER_USERNAME }}/landpred:latest